# Inspection

In [1]:
# Import libraries and configure pandas display options
import pandas as pd
from pathlib import Path

# Remove limits on columns, rows, and width for easier inspection
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)

In [2]:
# Define file paths and load raw CSVs into a dictionary
file_paths = {
    "order_reviews": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\order_reviews_dataset.csv",
    "orders": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\orders_dataset.csv",
    "product_category_translation": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\product_category_name_translation.csv",
    "products": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\products_dataset.csv",
    "sellers": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\sellers_dataset.csv",
    "closed_deals": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\closed_deals_dataset.csv",
    "customers": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\customers_dataset.csv",
    "geolocation": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\geolocation_dataset.csv",
    "marketing_qualified_leads": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\marketing_qualified_leads_dataset.csv",
    "order_items": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\order_items_dataset.csv",
    "order_payments": r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Raw\order_payments_dataset.csv",
}

tables = {}

# Iterate through paths, read CSVs, and confirm shape
for name, path in file_paths.items():
    tables[name] = pd.read_csv(path)
    print(f"{name} loaded successfully | Shape: {tables[name].shape}")

order_reviews loaded successfully | Shape: (99224, 7)
orders loaded successfully | Shape: (99441, 8)
product_category_translation loaded successfully | Shape: (71, 2)
products loaded successfully | Shape: (32951, 9)
sellers loaded successfully | Shape: (3095, 4)
closed_deals loaded successfully | Shape: (842, 14)
customers loaded successfully | Shape: (99441, 5)
geolocation loaded successfully | Shape: (1000163, 5)
marketing_qualified_leads loaded successfully | Shape: (8000, 4)
order_items loaded successfully | Shape: (112650, 7)
order_payments loaded successfully | Shape: (103886, 5)

In [3]:
# Define and run a comprehensive inspection function for each table
def inspect_table(df, table_name):
    # Print headers and shape
    print("=" * 80)
    print(f"TABLE: {table_name}")
    print("=" * 80)

    print("\nShape:")
    print(df.shape)

    # Print column names
    print("\nColumns:")
    print(df.columns.tolist())

    # Show first 5 rows
    print("\nFirst 5 rows:")
    display(df.head())

    # Show data types
    print("\nData types:")
    display(df.dtypes.to_frame("dtype"))

    # Calculate and display missing values and percentages
    print("\nMissing values:")
    missing = df.isna().sum().to_frame("missing_count")
    missing["missing_percent"] = (missing["missing_count"] / len(df) * 100).round(2)
    display(missing.sort_values("missing_count", ascending=False))

    # Count exact duplicates
    print("\nDuplicate rows:")
    print(df.duplicated().sum())

    # Summary statistics for numeric columns
    print("\nNumeric summary:")
    display(df.describe())

    # Summary statistics for text/categorical columns
    print("\nObject / categorical summary:")
    display(df.describe(include=["object", "str"]))
    
    # Show unique value counts per column
    print("\nUnique values per column:")
    display(df.nunique().to_frame("unique_values").sort_values("unique_values", ascending=False))

# Apply the function to all loaded tables
for name, df in tables.items():
    inspect_table(df, name)

================================================================================
TABLE: order_reviews
================================================================================

Shape:
(99224, 7)

Columns:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

First 5 rows:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

Data types:

                         dtype
review_id                  str
order_id                   str
review_score             int64
review_comment_title       str
review_comment_message     str
review_creation_date       str
review_answer_timestamp    str

Missing values:

                         missing_count  missing_percent
review_comment_title             87656            88.34
review_comment_message           58247            58.70
review_id                            0             0.00
review_score                         0             0.00
order_id                             0             0.00
review_creation_date                 0             0.00
review_answer_timestamp              0             0.00

Duplicate rows:
0

Numeric summary:

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

Object / categorical summary:

,review_id,order_id,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,99224,99224,11568,40977,99224,99224
unique,98410,98673,4527,36159,636,98248
top,c444278834184f72b1484dfe47de7f97,c88b1d1b157a9999ce368f218a407141,Recomendo,Muito bom,2017-12-19 00:00:00,2017-06-15 23:21:05
freq,3,3,423,230,463,4

Unique values per column:

                         unique_values
order_id                         98673
review_id                        98410
review_answer_timestamp          98248
review_comment_message           36159
review_comment_title              4527
review_creation_date               636
review_score                         5

================================================================================
TABLE: orders
================================================================================

Shape:
(99441, 8)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

First 5 rows:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

Data types:

                              dtype
order_id                        str
customer_id                     str
order_status                    str
order_purchase_timestamp        str
order_approved_at               str
order_delivered_carrier_date    str
order_delivered_customer_date   str
order_estimated_delivery_date   str

Missing values:

                               missing_count  missing_percent
order_delivered_customer_date           2965             2.98
order_delivered_carrier_date            1783             1.79
order_approved_at                        160             0.16
order_id                                   0             0.00
order_purchase_timestamp                   0             0.00
order_status                               0             0.00
customer_id                                0             0.00
order_estimated_delivery_date              0             0.00

Duplicate rows:
0

Numeric summary:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

Object / categorical summary:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

Unique values per column:

                               unique_values
order_id                               99441
customer_id                            99441
order_purchase_timestamp               98875
order_delivered_customer_date          95664
order_approved_at                      90733
order_delivered_carrier_date           81018
order_estimated_delivery_date            459
order_status                               8

================================================================================
TABLE: product_category_translation
================================================================================

Shape:
(71, 2)

Columns:
['product_category_name', 'product_category_name_english']

First 5 rows:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Data types:

                              dtype
product_category_name           str
product_category_name_english   str

Missing values:

                               missing_count  missing_percent
product_category_name                      0              0.0
product_category_name_english              0              0.0

Duplicate rows:
0

Numeric summary:

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

Object / categorical summary:

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

Unique values per column:

                               unique_values
product_category_name                     71
product_category_name_english             71

================================================================================
TABLE: products
================================================================================

Shape:
(32951, 9)

Columns:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

First 5 rows:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

Data types:

                              dtype
product_id                      str
product_category_name           str
product_name_lenght         float64
product_description_lenght  float64
product_photos_qty          float64
product_weight_g            float64
product_length_cm           float64
product_height_cm           float64
product_width_cm            float64

Missing values:

                            missing_count  missing_percent
product_category_name                 610             1.85
product_description_lenght            610             1.85
product_name_lenght                   610             1.85
product_photos_qty                    610             1.85
product_weight_g                        2             0.01
product_height_cm                       2             0.01
product_length_cm                       2             0.01
product_width_cm                        2             0.01
product_id                              0             0.00

Duplicate rows:
0

Numeric summary:

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

Object / categorical summary:

                              product_id product_category_name
count                              32951                 32341
unique                             32951                    73
top     1e9e8ef04dbcff4541ed26657ea517e5       cama_mesa_banho
freq                                   1                  3029

Unique values per column:

                            unique_values
product_id                          32951
product_description_lenght           2960
product_weight_g                     2204
product_height_cm                     102
product_length_cm                      99
product_width_cm                       95
product_category_name                  73
product_name_lenght                    66
product_photos_qty                     19

================================================================================
TABLE: sellers
================================================================================

Shape:
(3095, 4)

Columns:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

First 5 rows:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

Data types:

                        dtype
seller_id                 str
seller_zip_code_prefix  int64
seller_city               str
seller_state              str

Missing values:

                        missing_count  missing_percent
seller_id                           0              0.0
seller_zip_code_prefix              0              0.0
seller_city                         0              0.0
seller_state                        0              0.0

Duplicate rows:
0

Numeric summary:

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

Object / categorical summary:

                               seller_id seller_city seller_state
count                               3095        3095         3095
unique                              3095         611           23
top     3442f8959a84dea7ee197c632cb2df15   sao paulo           SP
freq                                   1         694         1849

Unique values per column:

                        unique_values
seller_id                        3095
seller_zip_code_prefix           2246
seller_city                       611
seller_state                       23

================================================================================
TABLE: closed_deals
================================================================================

Shape:
(842, 14)

Columns:
['mql_id', 'seller_id', 'sdr_id', 'sr_id', 'won_date', 'business_segment', 'lead_type', 'lead_behaviour_profile', 'has_company', 'has_gtin', 'average_stock', 'business_type', 'declared_product_catalog_size', 'declared_monthly_revenue']

First 5 rows:

,mql_id,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue
0,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0
1,a555fb36b9368110ede0f043dfc3b9a0,bbb7d7893a450660432ea6652310ebb7,09285259593c61296eef10c734121d5b,d3d1e91a157ea7f90548eef82f1955e3,2018-05-08 20:17:59,car_accessories,industry,eagle,NaN,NaN,NaN,reseller,NaN,0.0
2,327174d3648a2d047e8940d7d15204ca,612170e34b97004b3ba37eae81836b4c,b90f87164b5f8c2cfa5c8572834dbe3f,6565aa9ce3178a5caf6171827af3a9ba,2018-06-05 17:27:23,home_appliances,online_big,cat,NaN,NaN,NaN,reseller,NaN,0.0
3,f5fee8f7da74f4887f5bcae2bafb6dd6,21e1781e36faf92725dde4730a88ca0f,56bf83c4bb35763a51c2baab501b4c67,d3d1e91a157ea7f90548eef82f1955e3,2018-01-17 13:51:03,food_drink,online_small,NaN,NaN,NaN,NaN,reseller,NaN,0.0
4,ffe640179b554e295c167a2f6be528e0,ed8cb7b190ceb6067227478e48cf8dde,4b339f9567d060bcea4f5136b9f5949e,d3d1e91a157ea7f90548eef82f1955e3,2018-07-03 20:17:45,home_appliances,industry,wolf,NaN,NaN,NaN,manufacturer,NaN,0.0

Data types:

                                 dtype
mql_id                             str
seller_id                          str
sdr_id                             str
sr_id                              str
won_date                           str
business_segment                   str
lead_type                          str
lead_behaviour_profile             str
has_company                     object
has_gtin                        object
average_stock                      str
business_type                      str
declared_product_catalog_size  float64
declared_monthly_revenue       float64

Missing values:

                               missing_count  missing_percent
has_company                              779            92.52
has_gtin                                 778            92.40
average_stock                            776            92.16
declared_product_catalog_size            773            91.81
lead_behaviour_profile                   177            21.02
business_type                             10             1.19
lead_type                                  6             0.71
business_segment                           1             0.12
won_date                                   0             0.00
seller_id                                  0             0.00
mql_id                                     0             0.00
sr_id                                      0             0.00
sdr_id                                     0             0.00
declared_monthly_revenue                   0             0.00

Duplicate rows:
0

Numeric summary:

       declared_product_catalog_size  declared_monthly_revenue
count                      69.000000              8.420000e+02
mean                      233.028986              7.337768e+04
std                       352.380558              1.744799e+06
min                         1.000000              0.000000e+00
25%                        30.000000              0.000000e+00
50%                       100.000000              0.000000e+00
75%                       300.000000              0.000000e+00
max                      2000.000000              5.000000e+07

Object / categorical summary:

,mql_id,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type
count,842,842,842,842,842,841,836,665,63,64,66,832
unique,842,842,32,22,824,33,8,9,2,2,6,3
top,5420aad7fec3549a85876ba1c529bd84,2c43fb513632d29b3b58df74816f1b06,4b339f9567d060bcea4f5136b9f5949e,4ef15afb4b2723d8f3d81e51ec7afefe,2018-05-04 03:00:00,home_decor,online_medium,cat,True,True,5-20,reseller
freq,1,1,140,133,6,105,332,407,58,54,22,587

Unique values per column:

                               unique_values
mql_id                                   842
seller_id                                842
won_date                                 824
business_segment                          33
declared_product_catalog_size             33
sdr_id                                    32
declared_monthly_revenue                  27
sr_id                                     22
lead_behaviour_profile                     9
lead_type                                  8
average_stock                              6
business_type                              3
has_gtin                                   2
has_company                                2

================================================================================
TABLE: customers
================================================================================

Shape:
(99441, 5)

Columns:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

First 5 rows:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

Data types:

                          dtype
customer_id                 str
customer_unique_id          str
customer_zip_code_prefix  int64
customer_city               str
customer_state              str

Missing values:

                          missing_count  missing_percent
customer_id                           0              0.0
customer_unique_id                    0              0.0
customer_zip_code_prefix              0              0.0
customer_city                         0              0.0
customer_state                        0              0.0

Duplicate rows:
0

Numeric summary:

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

Object / categorical summary:

,customer_id,customer_unique_id,customer_city,customer_state
count,99441,99441,99441,99441
unique,99441,96096,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,sao paulo,SP
freq,1,17,15540,41746

Unique values per column:

                          unique_values
customer_id                       99441
customer_unique_id                96096
customer_zip_code_prefix          14994
customer_city                      4119
customer_state                       27

================================================================================
TABLE: geolocation
================================================================================

Shape:
(1000163, 5)

Columns:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

First 5 rows:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

Data types:

                               dtype
geolocation_zip_code_prefix    int64
geolocation_lat              float64
geolocation_lng              float64
geolocation_city                 str
geolocation_state                str

Missing values:

                             missing_count  missing_percent
geolocation_zip_code_prefix              0              0.0
geolocation_lat                          0              0.0
geolocation_lng                          0              0.0
geolocation_city                         0              0.0
geolocation_state                        0              0.0

Duplicate rows:
261831

Numeric summary:

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

Object / categorical summary:

       geolocation_city geolocation_state
count           1000163           1000163
unique             8011                27
top           sao paulo                SP
freq             135800            404268

Unique values per column:

                             unique_values
geolocation_lng                     717613
geolocation_lat                     717360
geolocation_zip_code_prefix          19015
geolocation_city                      8011
geolocation_state                       27

================================================================================
TABLE: marketing_qualified_leads
================================================================================

Shape:
(8000, 4)

Columns:
['mql_id', 'first_contact_date', 'landing_page_id', 'origin']

First 5 rows:

,mql_id,first_contact_date,landing_page_id,origin
0,dac32acd4db4c29c230538b72f8dd87d,2018-02-01,88740e65d5d6b056e0cda098e1ea6313,social
1,8c18d1de7f67e60dbd64e3c07d7e9d5d,2017-10-20,007f9098284a86ee80ddeb25d53e0af8,paid_search
2,b4bc852d233dfefc5131f593b538befa,2018-03-22,a7982125ff7aa3b2054c6e44f9d28522,organic_search
3,6be030b81c75970747525b843c1ef4f8,2018-01-22,d45d558f0daeecf3cccdffe3c59684aa,email
4,5420aad7fec3549a85876ba1c529bd84,2018-02-21,b48ec5f3b04e9068441002a19df93c6c,organic_search

Data types:

                   dtype
mql_id               str
first_contact_date   str
landing_page_id      str
origin               str

Missing values:

                    missing_count  missing_percent
origin                         60             0.75
mql_id                          0             0.00
first_contact_date              0             0.00
landing_page_id                 0             0.00

Duplicate rows:
0

Numeric summary:

,mql_id,first_contact_date,landing_page_id,origin
count,8000,8000,8000,7940
unique,8000,336,495,10
top,dac32acd4db4c29c230538b72f8dd87d,2018-05-02,b76ef37428e6799c421989521c0e5077,organic_search
freq,1,93,912,2296

Object / categorical summary:

,mql_id,first_contact_date,landing_page_id,origin
count,8000,8000,8000,7940
unique,8000,336,495,10
top,dac32acd4db4c29c230538b72f8dd87d,2018-05-02,b76ef37428e6799c421989521c0e5077,organic_search
freq,1,93,912,2296

Unique values per column:

                    unique_values
mql_id                       8000
landing_page_id               495
first_contact_date            336
origin                         10

================================================================================
TABLE: order_items
================================================================================

Shape:
(112650, 7)

Columns:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

First 5 rows:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

Data types:

                       dtype
order_id                 str
order_item_id          int64
product_id               str
seller_id                str
shipping_limit_date      str
price                float64
freight_value        float64

Missing values:

                     missing_count  missing_percent
order_id                         0              0.0
order_item_id                    0              0.0
product_id                       0              0.0
seller_id                        0              0.0
shipping_limit_date              0              0.0
price                            0              0.0
freight_value                    0              0.0

Duplicate rows:
0

Numeric summary:

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

Object / categorical summary:

,order_id,product_id,seller_id,shipping_limit_date
count,112650,112650,112650,112650
unique,98666,32951,3095,93318
top,8272b63d03f5f79c56e9e4120aec44ef,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,2018-03-01 02:50:48
freq,21,527,2033,21

Unique values per column:

                     unique_values
order_id                     98666
shipping_limit_date          93318
product_id                   32951
freight_value                 6999
price                         5968
seller_id                     3095
order_item_id                   21

================================================================================
TABLE: order_payments
================================================================================

Shape:
(103886, 5)

Columns:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

First 5 rows:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

Data types:

                        dtype
order_id                  str
payment_sequential      int64
payment_type              str
payment_installments    int64
payment_value         float64

Missing values:

                      missing_count  missing_percent
order_id                          0              0.0
payment_sequential                0              0.0
payment_type                      0              0.0
payment_installments              0              0.0
payment_value                     0              0.0

Duplicate rows:
0

Numeric summary:

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

Object / categorical summary:

                                order_id payment_type
count                             103886       103886
unique                             99440            5
top     fa65dad1b0e818e3ccc5cb0e39231352  credit_card
freq                                  29        76795

Unique values per column:

                      unique_values
order_id                      99440
payment_value                 29077
payment_sequential               29
payment_installments             24
payment_type                      5

In [4]:
# Check for duplicates in primary key columns
primary_key_checks = {
    "customers": "customer_id",
    "orders": "order_id",
    "products": "product_id",
    "sellers": "seller_id",
    "marketing_qualified_leads": "mql_id",
    "closed_deals": "mql_id",
    "product_category_translation": "product_category_name"
}

for table_name, key_col in primary_key_checks.items():
    df = tables[table_name]
    print(f"{table_name}.{key_col}")
    print("Rows:", len(df))
    print("Unique:", df[key_col].nunique())
    print("Duplicates:", df[key_col].duplicated().sum())
    print("-" * 50)

customers.customer_id
Rows: 99441
Unique: 99441
Duplicates: 0
--------------------------------------------------
orders.order_id
Rows: 99441
Unique: 99441
Duplicates: 0
--------------------------------------------------
products.product_id
Rows: 32951
Unique: 32951
Duplicates: 0
--------------------------------------------------
sellers.seller_id
Rows: 3095
Unique: 3095
Duplicates: 0
--------------------------------------------------
marketing_qualified_leads.mql_id
Rows: 8000
Unique: 8000
Duplicates: 0
--------------------------------------------------
closed_deals.mql_id
Rows: 842
Unique: 842
Duplicates: 0
--------------------------------------------------
product_category_translation.product_category_name
Rows: 71
Unique: 71
Duplicates: 0
--------------------------------------------------

In [5]:
# Check foreign key relationships for orphaned records
relationship_checks = [
    ("orders", "customer_id", "customers", "customer_id"),
    ("order_items", "order_id", "orders", "order_id"),
    ("order_items", "product_id", "products", "product_id"),
    ("order_items", "seller_id", "sellers", "seller_id"),
    ("order_payments", "order_id", "orders", "order_id"),
    ("order_reviews", "order_id", "orders", "order_id"),
    ("closed_deals", "mql_id", "marketing_qualified_leads", "mql_id"),
    ("closed_deals", "seller_id", "sellers", "seller_id"),
    ("products", "product_category_name", "product_category_translation", "product_category_name")
]

for left_table, left_key, right_table, right_key in relationship_checks:
    left_values = set(tables[left_table][left_key].dropna())
    right_values = set(tables[right_table][right_key].dropna())

    # Find values in the left table that don't exist in the right table
    unmatched = left_values - right_values

    print(f"{left_table}.{left_key} → {right_table}.{right_key}")
    print("Unmatched values:", len(unmatched))
    print("-" * 60)

orders.customer_id → customers.customer_id
Unmatched values: 0
------------------------------------------------------------
order_items.order_id → orders.order_id
Unmatched values: 0
------------------------------------------------------------
order_items.product_id → products.product_id
Unmatched values: 0
------------------------------------------------------------
order_items.seller_id → sellers.seller_id
Unmatched values: 0
------------------------------------------------------------
order_payments.order_id → orders.order_id
Unmatched values: 0
------------------------------------------------------------
order_reviews.order_id → orders.order_id
Unmatched values: 0
------------------------------------------------------------
closed_deals.mql_id → marketing_qualified_leads.mql_id
Unmatched values: 0
------------------------------------------------------------
closed_deals.seller_id → sellers.seller_id
Unmatched values: 462
------------------------------------------------------------
products.product_category_name → product_category_translation.product_category_name
Unmatched values: 2
------------------------------------------------------------

In [6]:
# Identify invalid date formats across specific columns
date_columns = {
    "orders": [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ],
    "order_items": ["shipping_limit_date"],
    "order_reviews": ["review_creation_date", "review_answer_timestamp"],
    "closed_deals": ["won_date"],
    "marketing_qualified_leads": ["first_contact_date"]
}

for table_name, cols in date_columns.items():
    print(f"\n{table_name}")
    for col in cols:
        converted = pd.to_datetime(tables[table_name][col], errors="coerce")
        invalid_count = converted.isna().sum() - tables[table_name][col].isna().sum()
        print(f"{col}: invalid dates = {invalid_count}")

orders
order_purchase_timestamp: invalid dates = 0
order_approved_at: invalid dates = 0
order_delivered_carrier_date: invalid dates = 0
order_delivered_customer_date: invalid dates = 0
order_estimated_delivery_date: invalid dates = 0

order_items
shipping_limit_date: invalid dates = 0

order_reviews
review_creation_date: invalid dates = 0
review_answer_timestamp: invalid dates = 0

closed_deals
won_date: invalid dates = 0

marketing_qualified_leads
first_contact_date: invalid dates = 0

In [7]:
# Check value distributions for key categorical columns
categorical_checks = {
    "orders": ["order_status"],
    "order_payments": ["payment_type"],
    "marketing_qualified_leads": ["origin"],
    "closed_deals": ["business_segment", "lead_type", "lead_behaviour_profile", "business_type"]
}

for table_name, cols in categorical_checks.items():
    print(f"\n{table_name}")
    for col in cols:
        print(f"\n{col}")
        display(tables[table_name][col].value_counts(dropna=False))

orders

order_status

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

order_payments

payment_type

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

marketing_qualified_leads

origin

origin
organic_search       2296
paid_search          1586
social               1350
unknown              1099
direct_traffic        499
email                 493
referral              284
other                 150
display               118
other_publicities      65
NaN                    60
Name: count, dtype: int64

closed_deals

business_segment

business_segment
home_decor                         105
health_beauty                       93
car_accessories                     77
household_utilities                 71
construction_tools_house_garden     69
audio_video_electronics             64
computers                           34
pet                                 30
food_supplement                     28
food_drink                          26
sports_leisure                      25
bed_bath_table                      22
bags_backpacks                      22
toys                                20
fashion_accessories                 19
home_office_furniture               14
stationery                          13
phone_mobile                        13
small_appliances                    12
handcrafted                         12
baby                                10
music_instruments                    9
books                                9
watches                              8
jewerly                              8
home_appliances                      7
party                                5
gifts                                5
other                                3
air_conditioning                     3
perfume                              2
games_consoles                       2
NaN                                  1
religious                            1
Name: count, dtype: int64

lead_type

lead_type
online_medium      332
online_big         126
industry           123
offline            104
online_small        77
online_beginner     57
online_top          14
NaN                  6
other                3
Name: count, dtype: int64

lead_behaviour_profile

lead_behaviour_profile
cat            407
NaN            177
eagle          123
wolf            95
shark           24
cat, wolf        8
eagle, wolf      3
eagle, cat       3
shark, cat       1
shark, wolf      1
Name: count, dtype: int64

business_type

business_type
reseller        587
manufacturer    242
NaN              10
other             3
Name: count, dtype: int64

# Cleaning

In [8]:
# Create a working copy of all tables for cleaning
cleaned_tables = {name: df.copy() for name, df in tables.items()}

In [9]:
# Correct spelling errors in column names
cleaned_tables["products"] = cleaned_tables["products"].rename(columns={
    "product_name_lenght": "product_name_length",
    "product_description_lenght": "product_description_length"
})

In [10]:
# Convert designated date strings into actual datetime objects
date_columns = {
    "orders": [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ],
    "order_items": ["shipping_limit_date"],
    "order_reviews": ["review_creation_date", "review_answer_timestamp"],
    "closed_deals": ["won_date"],
    "marketing_qualified_leads": ["first_contact_date"]
}

for table_name, cols in date_columns.items():
    for col in cols:
        cleaned_tables[table_name][col] = pd.to_datetime(
            cleaned_tables[table_name][col],
            errors="coerce"
        )

In [11]:
# Pad zip codes with leading zeros to maintain 5 digits
def clean_zip_prefix(series):
    """
    Converts zip code prefixes to 5-character strings.
    Useful for PostgreSQL and preserving zip-code style formatting.
    """
    return (
        series
        .astype("Int64")
        .astype("string")
        .str.zfill(5)
    )

zip_columns = {
    "customers": ["customer_zip_code_prefix"],
    "sellers": ["seller_zip_code_prefix"],
    "geolocation": ["geolocation_zip_code_prefix"]
}

for table_name, cols in zip_columns.items():
    for col in cols:
        cleaned_tables[table_name][col] = clean_zip_prefix(cleaned_tables[table_name][col])

In [12]:
# Standardize state abbreviations (uppercase, remove spaces)
def clean_state_column(series):
    """
    Standardizes Brazilian state abbreviations.
    """
    return (
        series
        .astype("string")
        .str.strip()
        .str.upper()
    )

state_columns = {
    "customers": ["customer_state"],
    "sellers": ["seller_state"],
    "geolocation": ["geolocation_state"]
}

for table_name, cols in state_columns.items():
    for col in cols:
        cleaned_tables[table_name][col] = clean_state_column(cleaned_tables[table_name][col])

In [13]:
# Standardize text columns (lowercase, strip, single spaces)
def clean_text_column(series):
    """
    Standardizes text values:
    - strips whitespace
    - converts to lowercase
    - replaces multiple spaces with single spaces
    """
    return (
        series
        .astype("string")
        .str.strip()
        .str.lower()
        .str.replace(r"\s+", " ", regex=True)
    )

text_columns = {
    "customers": ["customer_city"],
    "sellers": ["seller_city"],
    "geolocation": ["geolocation_city"],

    "orders": ["order_status"],

    "order_payments": ["payment_type"],

    "products": ["product_category_name"],

    "product_category_translation": [
        "product_category_name",
        "product_category_name_english"
    ],

    "marketing_qualified_leads": [
        "landing_page_id",
        "origin"
    ],

    "closed_deals": [
        "business_segment",
        "lead_type",
        "lead_behaviour_profile",
        "average_stock",
        "business_type"
    ]
}

for table_name, cols in text_columns.items():
    for col in cols:
        cleaned_tables[table_name][col] = clean_text_column(cleaned_tables[table_name][col])

In [14]:
# Fill missing categorical values with 'unknown'
cleaned_tables["marketing_qualified_leads"]["origin"] = (
    cleaned_tables["marketing_qualified_leads"]["origin"]
    .fillna("unknown")
)

closed_deal_unknown_cols = [
    "business_segment",
    "lead_type",
    "lead_behaviour_profile",
    "average_stock",
    "business_type"
]

for col in closed_deal_unknown_cols:
    cleaned_tables["closed_deals"][col] = cleaned_tables["closed_deals"][col].fillna("unknown")

cleaned_tables["products"]["product_category_name"] = (
    cleaned_tables["products"]["product_category_name"]
    .fillna("unknown")
)

In [15]:
# Map string representations to true boolean data types
bool_cols = ["has_company", "has_gtin"]

for col in bool_cols:
    cleaned_tables["closed_deals"][col] = (
        cleaned_tables["closed_deals"][col]
        .astype("string")
        .str.strip()
        .str.lower()
        .map({
            "true": True,
            "false": False,
            "1": True,
            "0": False
        })
        .astype("boolean")
    )

In [16]:
# Remove duplicate rows from the geolocation table
before_rows = len(cleaned_tables["geolocation"])

cleaned_tables["geolocation"] = (
    cleaned_tables["geolocation"]
    .drop_duplicates()
    .reset_index(drop=True)
)

after_rows = len(cleaned_tables["geolocation"])

print(f"Geolocation rows before removing duplicates: {before_rows}")
print(f"Geolocation rows after removing duplicates: {after_rows}")
print(f"Duplicate rows removed: {before_rows - after_rows}")

Geolocation rows before removing duplicates: 1000163
Geolocation rows after removing duplicates: 738332
Duplicate rows removed: 261831

In [17]:
# Sync product categories by appending missing ones to the translation table
products_categories = set(
    cleaned_tables["products"]["product_category_name"].dropna().unique()
)

translation_categories = set(
    cleaned_tables["product_category_translation"]["product_category_name"].dropna().unique()
)

# Find missing categories
missing_categories = sorted(products_categories - translation_categories)

# Create new dataframe rows
missing_category_rows = pd.DataFrame({
    "product_category_name": missing_categories,
    "product_category_name_english": missing_categories
})

# Append and drop potential duplicates
cleaned_tables["product_category_translation"] = pd.concat(
    [
        cleaned_tables["product_category_translation"],
        missing_category_rows
    ],
    ignore_index=True
).drop_duplicates(subset=["product_category_name"])

print("Missing product categories added to translation table:")
print(missing_categories)

Missing product categories added to translation table:
['pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos', 'unknown']

In [18]:
# Flag sellers in closed_deals based on their presence in sellers and orders tables
cleaned_tables["closed_deals"]["seller_exists_in_sellers"] = (
    cleaned_tables["closed_deals"]["seller_id"]
    .isin(cleaned_tables["sellers"]["seller_id"])
)

# Check if seller actually sold anything
converted_sellers_with_orders = set(cleaned_tables["order_items"]["seller_id"].unique())

cleaned_tables["closed_deals"]["seller_has_orders"] = (
    cleaned_tables["closed_deals"]["seller_id"]
    .isin(converted_sellers_with_orders)
)

In [19]:
# Output a summary of table shapes and missing values post-cleaning
cleaning_summary = []

for name, df in cleaned_tables.items():
    cleaning_summary.append({
        "table": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicate_rows": df.duplicated().sum(),
        "missing_values": df.isna().sum().sum()
    })

cleaning_summary_df = pd.DataFrame(cleaning_summary)
display(cleaning_summary_df)

,table,rows,columns,duplicate_rows,missing_values
0,order_reviews,99224,7,0,145903
1,orders,99441,8,0,4908
2,product_category_translation,74,2,0,0
3,products,32951,9,0,1838
4,sellers,3095,4,0,0
5,closed_deals,842,16,0,2330
6,customers,99441,5,0,0
7,geolocation,738332,5,0,0
8,marketing_qualified_leads,8000,4,0,0
9,order_items,112650,7,0,0
10,order_payments,103886,5,0,0

In [20]:
# Re-run foreign key check to ensure no new orphans were created
relationship_checks = [
    ("orders", "customer_id", "customers", "customer_id"),
    ("order_items", "order_id", "orders", "order_id"),
    ("order_items", "product_id", "products", "product_id"),
    ("order_items", "seller_id", "sellers", "seller_id"),
    ("order_payments", "order_id", "orders", "order_id"),
    ("order_reviews", "order_id", "orders", "order_id"),
    ("closed_deals", "mql_id", "marketing_qualified_leads", "mql_id"),
    ("closed_deals", "seller_id", "sellers", "seller_id"),
    ("products", "product_category_name", "product_category_translation", "product_category_name")
]

for left_table, left_key, right_table, right_key in relationship_checks:
    left_values = set(cleaned_tables[left_table][left_key].dropna())
    right_values = set(cleaned_tables[right_table][right_key].dropna())

    unmatched = left_values - right_values

    print(f"{left_table}.{left_key} → {right_table}.{right_key}")
    print("Unmatched values:", len(unmatched))
    print("-" * 60)

orders.customer_id → customers.customer_id
Unmatched values: 0
------------------------------------------------------------
order_items.order_id → orders.order_id
Unmatched values: 0
------------------------------------------------------------
order_items.product_id → products.product_id
Unmatched values: 0
------------------------------------------------------------
order_items.seller_id → sellers.seller_id
Unmatched values: 0
------------------------------------------------------------
order_payments.order_id → orders.order_id
Unmatched values: 0
------------------------------------------------------------
order_reviews.order_id → orders.order_id
Unmatched values: 0
------------------------------------------------------------
closed_deals.mql_id → marketing_qualified_leads.mql_id
Unmatched values: 0
------------------------------------------------------------
closed_deals.seller_id → sellers.seller_id
Unmatched values: 462
------------------------------------------------------------
products.product_category_name → product_category_translation.product_category_name
Unmatched values: 0
------------------------------------------------------------

In [21]:
# Extract year, month, and month_start from MQL contacts for analysis
mql = cleaned_tables["marketing_qualified_leads"]

mql["first_contact_year"] = mql["first_contact_date"].dt.year
mql["first_contact_month"] = mql["first_contact_date"].dt.month
mql["first_contact_month_start"] = mql["first_contact_date"].dt.to_period("M").dt.to_timestamp()

cleaned_tables["marketing_qualified_leads"] = mql

In [22]:
# Calculate sales cycle length (days to close) and flag invalid cycles
closed_deals = cleaned_tables["closed_deals"]
mql_dates = cleaned_tables["marketing_qualified_leads"][["mql_id", "first_contact_date"]]

# Bring in contact dates
closed_deals = closed_deals.merge(
    mql_dates,
    on="mql_id",
    how="left"
)

closed_deals["won_year"] = closed_deals["won_date"].dt.year
closed_deals["won_month"] = closed_deals["won_date"].dt.month
closed_deals["won_month_start"] = closed_deals["won_date"].dt.to_period("M").dt.to_timestamp()

# Calculate cycle time in days
closed_deals["days_to_close"] = (
    closed_deals["won_date"] - closed_deals["first_contact_date"]
).dt.days

# Flag negative or invalid close times
closed_deals["is_valid_sales_cycle"] = closed_deals["days_to_close"] >= 0

cleaned_tables["closed_deals"] = closed_deals

In [23]:
# Calculate delivery metrics (delays, estimated times, and late flags)
orders = cleaned_tables["orders"]

orders["purchase_year"] = orders["order_purchase_timestamp"].dt.year
orders["purchase_month"] = orders["order_purchase_timestamp"].dt.month
orders["purchase_month_start"] = orders["order_purchase_timestamp"].dt.to_period("M").dt.to_timestamp()

orders["approval_days"] = (
    orders["order_approved_at"] - orders["order_purchase_timestamp"]
).dt.total_seconds() / 86400

orders["delivery_days"] = (
    orders["order_delivered_customer_date"] - orders["order_purchase_timestamp"]
).dt.total_seconds() / 86400

orders["estimated_delivery_days"] = (
    orders["order_estimated_delivery_date"] - orders["order_purchase_timestamp"]
).dt.total_seconds() / 86400

# Delay calculation (actual - estimated)
orders["delivery_delay_days"] = (
    orders["order_delivered_customer_date"] - orders["order_estimated_delivery_date"]
).dt.total_seconds() / 86400

# Flag if delivered past the estimated date
orders["is_late_delivery"] = orders["delivery_delay_days"] > 0

cleaned_tables["orders"] = orders

In [24]:
# Add combined order value (price + freight)
order_items = cleaned_tables["order_items"]

order_items["item_total_value"] = order_items["price"] + order_items["freight_value"]

cleaned_tables["order_items"] = order_items

In [25]:
# Calculate total product volume (L x W x H)
products = cleaned_tables["products"]

products["product_volume_cm3"] = (
    products["product_length_cm"]
    * products["product_height_cm"]
    * products["product_width_cm"]
)

cleaned_tables["products"] = products

In [26]:
# Create flag for text reviews and calculate review response times
reviews = cleaned_tables["order_reviews"]

reviews["has_review_comment"] = reviews["review_comment_message"].notna()

reviews["review_response_time_hours"] = (
    reviews["review_answer_timestamp"] - reviews["review_creation_date"]
).dt.total_seconds() / 3600

cleaned_tables["order_reviews"] = reviews

In [27]:
# Flag orders paid using multiple installments
payments = cleaned_tables["order_payments"]

payments["is_installment_payment"] = payments["payment_installments"] > 1

cleaned_tables["order_payments"] = payments

In [28]:
# Output heads of the newly derived columns to visually verify
derived_columns_check = {
    "marketing_qualified_leads": [
        "first_contact_year",
        "first_contact_month",
        "first_contact_month_start"
    ],
    "closed_deals": [
        "first_contact_date",
        "won_year",
        "won_month",
        "won_month_start",
        "days_to_close",
        "is_valid_sales_cycle"
    ],
    "orders": [
        "purchase_year",
        "purchase_month",
        "purchase_month_start",
        "approval_days",
        "delivery_days",
        "estimated_delivery_days",
        "delivery_delay_days",
        "is_late_delivery"
    ],
    "order_items": [
        "item_total_value"
    ],
    "products": [
        "product_volume_cm3"
    ],
    "order_reviews": [
        "has_review_comment",
        "review_response_time_hours"
    ],
    "order_payments": [
        "is_installment_payment"
    ]
}

for table_name, cols in derived_columns_check.items():
    print("=" * 80)
    print(table_name)
    print("=" * 80)
    display(cleaned_tables[table_name][cols].head())

================================================================================
marketing_qualified_leads
================================================================================

   first_contact_year  first_contact_month first_contact_month_start
0                2018                    2                2018-02-01
1                2017                   10                2017-10-01
2                2018                    3                2018-03-01
3                2018                    1                2018-01-01
4                2018                    2                2018-02-01

================================================================================
closed_deals
================================================================================

,first_contact_date,won_year,won_month,won_month_start,days_to_close,is_valid_sales_cycle
0,2018-02-21,2018,2,2018-02-01,5,True
1,2018-04-04,2018,5,2018-05-01,34,True
2,2018-04-03,2018,6,2018-06-01,63,True
3,2018-01-14,2018,1,2018-01-01,3,True
4,2017-10-09,2018,7,2018-07-01,267,True

================================================================================
orders
================================================================================

,purchase_year,purchase_month,purchase_month_start,approval_days,delivery_days,estimated_delivery_days,delivery_delay_days,is_late_delivery
0,2017,10,2017-10-01,0.007431,8.436574,15.544063,-7.107488,False
1,2018,7,2018-07-01,1.279745,13.782037,19.137766,-5.355729,False
2,2018,8,2018-08-01,0.011505,9.394213,26.639711,-17.245498,False
3,2017,11,2017-11-01,0.012419,13.208750,26.188819,-12.980069,False
4,2018,2,2018-02-01,0.042940,2.873877,12.112049,-9.238171,False

================================================================================
order_items
================================================================================

   item_total_value
0             72.19
1            259.83
2            216.87
3             25.78
4            218.04

================================================================================
products
================================================================================

   product_volume_cm3
0              2240.0
1             10800.0
2              2430.0
3              2704.0
4              4420.0

================================================================================
order_reviews
================================================================================

   has_review_comment  review_response_time_hours
0               False                   21.783056
1               False                   27.086944
2               False                   38.606667
3                True                   22.035000
4                True                   34.448056

================================================================================
order_payments
================================================================================

   is_installment_payment
0                    True
1                   False
2                   False
3                    True
4                    True

In [29]:
# Locate anomalous calculated values (negatives or zeros)
print("Closed deals with negative days_to_close:")
display(
    cleaned_tables["closed_deals"]
    .loc[cleaned_tables["closed_deals"]["days_to_close"] < 0,
         ["mql_id", "first_contact_date", "won_date", "days_to_close"]]
)

print("Orders with negative delivery_days:")
display(
    cleaned_tables["orders"]
    .loc[cleaned_tables["orders"]["delivery_days"] < 0,
         ["order_id", "order_purchase_timestamp", "order_delivered_customer_date", "delivery_days"]]
)

print("Orders with negative approval_days:")
display(
    cleaned_tables["orders"]
    .loc[cleaned_tables["orders"]["approval_days"] < 0,
         ["order_id", "order_purchase_timestamp", "order_approved_at", "approval_days"]]
)

print("Products with zero or missing volume:")
display(
    cleaned_tables["products"]
    .loc[
        (cleaned_tables["products"]["product_volume_cm3"].isna()) |
        (cleaned_tables["products"]["product_volume_cm3"] <= 0),
        ["product_id", "product_length_cm", "product_height_cm", "product_width_cm", "product_volume_cm3"]
    ]
)

Closed deals with negative days_to_close:

,mql_id,first_contact_date,won_date,days_to_close
667,b91cf8812365f50ff4bda4bcd6206b05,2018-03-08,2018-03-06 19:38:55,-2

Orders with negative delivery_days:

Empty DataFrame
Columns: [order_id, order_purchase_timestamp, order_delivered_customer_date, delivery_days]
Index: []

Orders with negative approval_days:

Empty DataFrame
Columns: [order_id, order_purchase_timestamp, order_approved_at, approval_days]
Index: []

Products with zero or missing volume:

,product_id,product_length_cm,product_height_cm,product_width_cm,product_volume_cm3
8578,09ff539a621711667c43eba6a3bd8466,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN

In [30]:
# Output updated table summary showing new column counts
updated_summary = []

for name, df in cleaned_tables.items():
    updated_summary.append({
        "table": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicate_rows": df.duplicated().sum(),
        "missing_values": df.isna().sum().sum()
    })

updated_summary_df = pd.DataFrame(updated_summary)
display(updated_summary_df)

,table,rows,columns,duplicate_rows,missing_values
0,order_reviews,99224,9,0,145903
1,orders,99441,16,0,10998
2,product_category_translation,74,2,0,0
3,products,32951,10,0,1840
4,sellers,3095,4,0,0
5,closed_deals,842,22,0,2330
6,customers,99441,5,0,0
7,geolocation,738332,5,0,0
8,marketing_qualified_leads,8000,7,0,0
9,order_items,112650,8,0,0
10,order_payments,103886,6,0,0

In [31]:
# Mask out negative sales cycles with pd.NA
closed_deals = cleaned_tables["closed_deals"]

closed_deals["is_valid_sales_cycle"] = closed_deals["days_to_close"] >= 0

# Replace negatives with NA
closed_deals.loc[
    closed_deals["days_to_close"] < 0,
    "days_to_close"
] = pd.NA

cleaned_tables["closed_deals"] = closed_deals

In [32]:
# Convert `is_late_delivery` to nullable boolean and handle NAs
orders = cleaned_tables["orders"]

orders["is_late_delivery"] = pd.NA

orders.loc[
    orders["order_delivered_customer_date"].notna(),
    "is_late_delivery"
] = orders.loc[
    orders["order_delivered_customer_date"].notna(),
    "delivery_delay_days"
] > 0

orders["is_late_delivery"] = orders["is_late_delivery"].astype("boolean")

cleaned_tables["orders"] = orders

In [33]:
# Verify previously detected anomalies were resolved
print("Invalid sales cycles:")
display(
    cleaned_tables["closed_deals"]
    .loc[
        cleaned_tables["closed_deals"]["is_valid_sales_cycle"] == False,
        ["mql_id", "first_contact_date", "won_date", "days_to_close", "is_valid_sales_cycle"]
    ]
)

print("Late delivery value counts:")
display(cleaned_tables["orders"]["is_late_delivery"].value_counts(dropna=False))

print("Product volume missing:")
display(
    cleaned_tables["products"]
    .loc[
        cleaned_tables["products"]["product_volume_cm3"].isna(),
        ["product_id", "product_volume_cm3"]
    ]
)

Invalid sales cycles:

,mql_id,first_contact_date,won_date,days_to_close,is_valid_sales_cycle
667,b91cf8812365f50ff4bda4bcd6206b05,2018-03-08,2018-03-06 19:38:55,NaN,False

Late delivery value counts:

is_late_delivery
False    88649
True      7827
<NA>      2965
Name: count, dtype: Int64

Product volume missing:

                             product_id  product_volume_cm3
8578   09ff539a621711667c43eba6a3bd8466                 NaN
18851  5eb564652db742ff8f28759cd8d2652a                 NaN

In [34]:
# Final validation summary before export
final_validation = []

for name, df in cleaned_tables.items():
    final_validation.append({
        "table": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicate_rows": df.duplicated().sum(),
        "missing_values": df.isna().sum().sum()
    })

final_validation_df = pd.DataFrame(final_validation)

display(final_validation_df)

,table,rows,columns,duplicate_rows,missing_values
0,order_reviews,99224,9,0,145903
1,orders,99441,16,0,13963
2,product_category_translation,74,2,0,0
3,products,32951,10,0,1840
4,sellers,3095,4,0,0
5,closed_deals,842,22,0,2331
6,customers,99441,5,0,0
7,geolocation,738332,5,0,0
8,marketing_qualified_leads,8000,7,0,0
9,order_items,112650,8,0,0
10,order_payments,103886,6,0,0

In [35]:
# Confirm final datatypes of all tables
for name, df in cleaned_tables.items():
    print("=" * 80)
    print(name)
    print("=" * 80)
    display(df.dtypes.to_frame("dtype"))

================================================================================
order_reviews
================================================================================

                                     dtype
review_id                              str
order_id                               str
review_score                         int64
review_comment_title                   str
review_comment_message                 str
review_creation_date        datetime64[us]
review_answer_timestamp     datetime64[us]
has_review_comment                    bool
review_response_time_hours         float64

================================================================================
orders
================================================================================

                                        dtype
order_id                                  str
customer_id                               str
order_status                           string
order_purchase_timestamp       datetime64[us]
order_approved_at              datetime64[us]
order_delivered_carrier_date   datetime64[us]
order_delivered_customer_date  datetime64[us]
order_estimated_delivery_date  datetime64[us]
purchase_year                           int32
purchase_month                          int32
purchase_month_start           datetime64[us]
approval_days                         float64
delivery_days                         float64
estimated_delivery_days               float64
delivery_delay_days                   float64
is_late_delivery                      boolean

================================================================================
product_category_translation
================================================================================

                                dtype
product_category_name          string
product_category_name_english  string

================================================================================
products
================================================================================

                              dtype
product_id                      str
product_category_name        string
product_name_length         float64
product_description_length  float64
product_photos_qty          float64
product_weight_g            float64
product_length_cm           float64
product_height_cm           float64
product_width_cm            float64
product_volume_cm3          float64

================================================================================
sellers
================================================================================

                         dtype
seller_id                  str
seller_zip_code_prefix  string
seller_city             string
seller_state            string

================================================================================
closed_deals
================================================================================

                                        dtype
mql_id                                    str
seller_id                                 str
sdr_id                                    str
sr_id                                     str
won_date                       datetime64[us]
business_segment                       string
lead_type                              string
lead_behaviour_profile                 string
has_company                           boolean
has_gtin                              boolean
average_stock                          string
business_type                          string
declared_product_catalog_size         float64
declared_monthly_revenue              float64
seller_exists_in_sellers                 bool
seller_has_orders                        bool
first_contact_date             datetime64[us]
won_year                                int32
won_month                               int32
won_month_start                datetime64[us]
days_to_close                         float64
is_valid_sales_cycle                     bool

================================================================================
customers
================================================================================

                           dtype
customer_id                  str
customer_unique_id           str
customer_zip_code_prefix  string
customer_city             string
customer_state            string

================================================================================
geolocation
================================================================================

                               dtype
geolocation_zip_code_prefix   string
geolocation_lat              float64
geolocation_lng              float64
geolocation_city              string
geolocation_state             string

================================================================================
marketing_qualified_leads
================================================================================

                                    dtype
mql_id                                str
first_contact_date         datetime64[us]
landing_page_id                    string
origin                             string
first_contact_year                  int32
first_contact_month                 int32
first_contact_month_start  datetime64[us]

================================================================================
order_items
================================================================================

                              dtype
order_id                        str
order_item_id                 int64
product_id                      str
seller_id                       str
shipping_limit_date  datetime64[us]
price                       float64
freight_value               float64
item_total_value            float64

================================================================================
order_payments
================================================================================

                          dtype
order_id                    str
payment_sequential        int64
payment_type             string
payment_installments      int64
payment_value           float64
is_installment_payment     bool

In [36]:
# Print min and max bounds for all primary date columns
date_range_checks = {
    "marketing_qualified_leads": "first_contact_date",
    "closed_deals": "won_date",
    "orders": "order_purchase_timestamp",
    "order_reviews": "review_creation_date"
}

for table_name, date_col in date_range_checks.items():
    df = cleaned_tables[table_name]

    print(f"{table_name}.{date_col}")
    print("Min date:", df[date_col].min())
    print("Max date:", df[date_col].max())
    print("-" * 60)

marketing_qualified_leads.first_contact_date
Min date: 2017-06-14 00:00:00
Max date: 2018-05-31 00:00:00
------------------------------------------------------------
closed_deals.won_date
Min date: 2017-12-05 02:00:00
Max date: 2018-11-14 18:04:19
------------------------------------------------------------
orders.order_purchase_timestamp
Min date: 2016-09-04 21:15:19
Max date: 2018-10-17 17:30:18
------------------------------------------------------------
order_reviews.review_creation_date
Min date: 2016-10-02 00:00:00
Max date: 2018-08-31 00:00:00
------------------------------------------------------------

# Exporting

In [37]:
# Export the fully cleaned tables to the Processed directory
processed_path = Path(
    r"D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed"
)

# Ensure folder exists
processed_path.mkdir(parents=True, exist_ok=True)

# Export loop
for table_name, df in cleaned_tables.items():
    output_file = processed_path / f"{table_name}.csv"
    
    df.to_csv(
        output_file,
        index=False,
        encoding="utf-8",
        na_rep=""
    )
    
    print(f"Exported: {output_file}")

Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\order_reviews.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\orders.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\product_category_translation.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\products.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\sellers.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\closed_deals.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\customers.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\geolocation.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\marketing_qualified_leads.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\order_items.csv
Exported: D:\Data_Science\Projects\Portfolio_Projects\Marketing-Funnel-Seller-Performance-and-Revenue-Impact\Dataset\Processed\order_payments.csv

In [38]:
# Verify exported files in the destination path
exported_files = list(processed_path.glob("*.csv"))

print(f"Total exported files: {len(exported_files)}")

for file in exported_files:
    print(file.name)

Total exported files: 11
closed_deals.csv
customers.csv
geolocation.csv
marketing_qualified_leads.csv
orders.csv
order_items.csv
order_payments.csv
order_reviews.csv
products.csv
product_category_translation.csv
sellers.csv